### ISSUE TITLE
rabbitmq1 exited with code 1

### ISSUE THREAD

**Issue by abc13051305** [serkodev/rabbitmq-cluster-docker#1]
After I clone the repository, I run the command  "docker compose up", i have this error :
rabbitmq-cluster-docker-rabbitmq1-1  |Applications 'rabbit_and_plugins' are running on node 'rabbit@rabbitmq1'
rabbitmq-cluster-docker-rabbitmq1-1  | tail: cannot open '/var/log/rabbitmq/*.log' for reading: No such file or directory
rabbitmq-cluster-docker-rabbitmq1-1  | tail: no files remaining
rabbitmq-cluster-docker-rabbitmq1-1 exited with code 1

Because the rabbitmq1  exited,the container 'rabbitmq2' and 'rabbitmq3' can't connect rabbitmq1.
Then,have the log:
rabbitmq-cluster-docker-rabbitmq3-1 exited with code 69
rabbitmq-cluster-docker-rabbitmq2-1 exited with code 69

I have tyied it in another new vm,but I still see the error log.
can anybody help ~~

Thanks.

**Comment by serkodev** [comment]
Can you let me know your OS and Docker version? I just tried it once and haven't found the problem you mentioned.

**Comment by fanlun008** [comment]
Hi, same error, 
OS: macos 10.15.7 
docker desktop: 
 - Version 4.15.0 (93002)
 - Engine: 20.10.21
 - Compose: v2.13.0

May you help check? Thanks a lot.

> Can you let me know your OS and Docker version? I just tried it once and haven't found the problem you mentioned.

**Comment by fduran** [comment]
The RMQ official Docker image doesn't log to a file but to [console](https://github.com/docker-library/rabbitmq/blob/master/conf.d/10-defaults.conf#L12), as it's standard for containers. (This behavior can be overruled with a `RABBITMQ_LOGS` [env var](https://www.rabbitmq.com/logging.html#log-file-location) ) 

This can be checked by looking at the Docker logs of a container created with this image:
```
docker logs rmq |grep Logs
  Logs: <stdout>
```

So there's a `/var/log/rabbitmq` directory in the container but it has no files, hence the error.

This can be verified by for ex by creating a container from the image `docker run -d --name rmq rabbitmq:3-management` and running `docker exec -ti rmq ls -l /var/log/rabbitmq`.

Changing https://github.com/serkodev/rabbitmq-cluster-docker/blob/master/cluster-entrypoint.sh#L26 to an existing file works for example.

**Comment by maMykola** [comment]
you can replace this line with
```shell
tail -f /dev/null
```

**Comment by fduran** [comment]
> you can replace this line with
> 
> ```shell
> tail -f /dev/null
> ```

Yes, this is even better and pretty standard I think, thanks.

**Comment by serkodev** [comment]
@maMykola Amazing! Feel free to submit a Pull Request if possible, hope to give you credit for the contribution.

**Comment by maMykola** [comment]
> @maMykola Amazing! Feel free to submit a Pull Request if possible, hope to give you credit for the contribution.

https://github.com/serkodev/rabbitmq-cluster-docker/pull/2
