### ISSUE TITLE
How add nginx for web ui?

### ISSUE THREAD

**Issue by podruge** [serkodev/rabbitmq-cluster-docker#5]
Hi bro! How i can add nginx for listen rabbitmq web ui as external link?

**Comment by L-U-C-K-Y** [comment]
@podruge the project uses ha-proxy instead of nginx and the management UI is exposed on port 15672.

Could you clarify what you mean?

**Comment by podruge** [comment]
@L-U-C-K-Y 

I asked some nonsense, even before I realized that the web interface was already available out of the box. Thank you.
